<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ $chapter->title }} - Export</title>
    <style>
        body {
            font-family: 'Inter', sans-serif;
            padding: 40px;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #000;
            padding-bottom: 20px;
            margin-bottom: 40px;
        }

        .question {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }

        .question-text {
            font-weight: bold;
            margin-bottom: 10px;
        }

        .options {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
        }

        .footer {
            margin-top: 50px;
            font-size: 0.8rem;
            color: #666;
            text-align: center;
        }

        @media print {
            .no-print {
                display: none;
            }
        }
    </style>
</head>

<body>
    <div class="no-print"
        style="background: #f8f9fa; padding: 20px; text-align: center; margin-bottom: 40px; border-radius: 8px;">
        <button onclick="window.print()"
            style="padding: 10px 20px; background: #0d6efd; color: white; border: none; border-radius: 5px; cursor: pointer;">
            Print / Save as PDF
        </button>
    </div>

    <div class="header">
        <h1>{{ $chapter->book->title }}</h1>
        <h2>Chapter: {{ $chapter->title }}</h2>
    </div>

    <div class="content">
        @foreach ($chapter->questions as $index => $q)
            <div class="question">
                <div class="question-text">{{ $index + 1 }}. {{ $q->question }}</div>
                <div class="options">
                    <div>(A) {{ $q->option_a }}</div>
                    <div>(B) {{ $q->option_b }}</div>
                    <div>(C) {{ $q->option_c }}</div>
                    <div>(D) {{ $q->option_d }}</div>
                </div>
            </div>
        @endforeach
    </div>

    <div class="footer">
        Generated by Quizzer Platform — {{ now()->format('Y-m-d H:i') }}
    </div>
</body>

</html>
